FROM maven:3.8.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-jammy
# Use /deploy instead of /app to protect our code file
WORKDIR /deploy
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY --from=build /app/target/app.jar /deploy/app.jar
EXPOSE 8000
ENTRYPOINT ["java", "-jar", "/deploy/app.jar"]
